<?php

namespace MauticPlugin\LeuchtfeuerCompanySegmentsBundle\Controller;

use Doctrine\Persistence\ManagerRegistry;
use Mautic\CoreBundle\Factory\MauticFactory;
use Mautic\CoreBundle\Factory\ModelFactory;
use Mautic\CoreBundle\Helper\CoreParametersHelper;
use Mautic\CoreBundle\Helper\UserHelper;
use Mautic\CoreBundle\Security\Permissions\CorePermissions;
use Mautic\CoreBundle\Service\FlashBag;
use Mautic\CoreBundle\Translation\Translator;
use Mautic\FormBundle\Helper\FormFieldHelper;
use Mautic\LeadBundle\Entity\Company;
use Mautic\LeadBundle\Model\CompanyModel;
use MauticPlugin\LeuchtfeuerCompanySegmentsBundle\Model\CompanyEventLogModel;
use MauticPlugin\LeuchtfeuerCompanyTagsBundle\Controller\CompanyController as CompanyTagsController;
use MauticPlugin\LeuchtfeuerCompanyTagsBundle\Integration\Config;
use MauticPlugin\LeuchtfeuerCompanyTagsBundle\Model\CompanyTagModel;
use Symfony\Component\EventDispatcher\EventDispatcherInterface;
use Symfony\Component\Form\FormFactoryInterface;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\RequestStack;
use Symfony\Component\HttpFoundation\Response;

class CompanyController extends CompanyTagsController
{
    // @phpstan-ignore-next-line
    public function __construct(
        FormFactoryInterface $formFactory,
        FormFieldHelper $fieldHelper,
        ManagerRegistry $managerRegistry,
        MauticFactory $factory,
        ModelFactory $modelFactory,
        UserHelper $userHelper,
        CoreParametersHelper $coreParametersHelper,
        EventDispatcherInterface $dispatcher,
        Translator $translator,
        FlashBag $flashBag,
        public RequestStack $requestStack,
        CorePermissions $security,
        private CompanyTagModel $companyTagModel,
        private Config $config,
        private CompanyEventLogModel $companyEventLogModel,
    ) {
        parent::__construct(
            $formFactory,
            $fieldHelper,
            $managerRegistry,
            $factory,
            $modelFactory,
            $userHelper,
            $coreParametersHelper,
            $dispatcher,
            $translator,
            $flashBag,
            $requestStack,
            $security,
            $companyTagModel,
            $config
        );
    }

    /**
     * @param int $objectId
     *
     * @return RedirectResponse|JsonResponse|array<mixed>|Response
     */
    public function viewAction(Request $request, $objectId): RedirectResponse|JsonResponse|array|Response
    {
        if (!$this->config->isPublished()) {
            return parent::viewAction($request, $objectId); // TODO: Change the autogenerated stub
        }

        /** @var CompanyModel $model */
        $model  = $this->getModel('lead.company');

        $company = $model->getEntity($objectId);

        // set the return URL
        $returnUrl = $this->generateUrl('mautic_company_index');

        $postActionVars = [
            'returnUrl'       => $returnUrl,
            'contentTemplate' => 'Mautic\LeadBundle\Controller\CompanyController::indexAction',
            'passthroughVars' => [
                'activeLink'    => '#mautic_company_index',
                'mauticContent' => 'company',
            ],
        ];

        if (null === $company) {
            return $this->postActionRedirect(
                array_merge(
                    $postActionVars,
                    [
                        'flashes' => [
                            [
                                'type'    => 'error',
                                'msg'     => 'mautic.company.error.notfound',
                                'msgVars' => ['%id%' => $objectId],
                            ],
                        ],
                    ]
                )
            );
        }

        /** @var Company $company */
        $model->getRepository()->refetchEntity($company);

        // set some permissions
        $permissions = $this->security->isGranted(
            [
                'lead:leads:viewown',
                'lead:leads:viewother',
                'lead:leads:create',
                'lead:leads:editown',
                'lead:leads:editother',
                'lead:leads:deleteown',
                'lead:leads:deleteother',
            ],
            'RETURN_ARRAY'
        );

        if (!$this->security->hasEntityAccess(
            'lead:leads:viewown',
            'lead:leads:viewother',
            $company->getPermissionUser()
        )
        ) {
            return $this->accessDenied();
        }

        $fields         = $company->getFields();
        $contacts       = $model->getCompanyLeadRepository()->getCompanyLeads($objectId);

        $leadIds = array_column($contacts, 'lead_id');

        $contacts = $this->getCompanyContacts($request, $objectId, 0, $leadIds);

        return $this->delegateView(
            [
                'viewParameters' => [
                    'company'           => $company,
                    'tags'              => $this->companyTagModel->getTagsByCompany($company),
                    'fields'            => $fields,
                    'items'             => $contacts['items'],
                    'permissions'       => $permissions,
                    'engagementData'    => $this->getCompanyEngagementsForGraph($contacts),
                    'security'          => $this->security,
                    'page'              => $contacts['page'],
                    'totalItems'        => $contacts['count'],
                    'limit'             => $contacts['limit'],
                    'events'            => $this->getCompanyEngagements($company),
                ],
                'contentTemplate' => '@LeuchtfeuerCompanySegments/Company/company.html.twig',
            ]
        );
    }

    /**
     * @param int $page
     * @param int $limit
     */
    protected function getCompanyEngagements(Company $company, ?array $filters = null, ?array $orderBy = null, $page = 1, $limit = 25): array
    {
        $session = $this->requestStack->getCurrentRequest()->getSession();

        if (null == $filters) {
            $filters = $session->get(
                'mautic.company.'.$company->getId().'.timeline.filters',
                [
                    'search'        => '',
                    'includeEvents' => [],
                    'excludeEvents' => [],
                ]
            );
        }

        if (null == $orderBy) {
            if (!$session->has('mautic.company.'.$company->getId().'.timeline.orderby')) {
                $session->set('mautic.company.'.$company->getId().'.timeline.orderby', 'timestamp');
                $session->set('mautic.company.'.$company->getId().'.timeline.orderbydir', 'DESC');
            }

            $orderBy = [
                $session->get('mautic.company.'.$company->getId().'.timeline.orderby'),
                $session->get('mautic.company.'.$company->getId().'.timeline.orderbydir'),
            ];
        }

        return $this->companyEventLogModel->getEngagements($company, $filters, $orderBy, $page, $limit);
    }
}
